
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: user # You can set this to "create" if you want the schema to be created every time
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080